project_folder := "/home/ubuntu/gr00t"

default:
  just --list

setup-gr00t:
  cd {{ project_folder }} && \
  sudo apt install svt-av1 ffmpeg && \
  UV_PYTHON=python3.10 uv init && \
  mkdir outputs && \
  mkdir vendor && cd vendor && \
  git config --global credential.helper store && \
  git clone https://github.com/huggingface/lerobot.git && \
  cd lerobot && \
  git checkout v0.4.0 && \
  uv venv && \
  uv pip install "torch>=2.2.1,<2.8.0" "torchvision>=0.21.0,<0.23.0" && \
  uv pip install ninja "packaging>=24.2,<26.0" && \
  uv pip install "flash-attn>=2.5.9,<3.0.0" && \
  uv pip install -e .[all,groot] && \
  uv pip uninstall transformers && \
  uv pip install transformers

train-lerobot-grootn15:
  uv run lerobot-train \
      --dataset.repo_id=felixmayor/record-candle-cake \
      --job_name=groot_candle_training \
      --output_dir={{ project_folder }}/outputs/gr00t_candle_training \
      --policy.type=groot \
      --policy.push_to_hub=false \
      --policy.repo_id={{ project_folder }}/outputs/groot_candle \
      --policy.tune_diffusion_model=false \
      --wandb.enable=false \
      --wandb.disable_artifact=true \
      --save_checkpoint=true \
      --log_freq=100 \
      --save_freq=5000 \
      --steps=1 \
      --policy.device=cuda \
      --batch_size=32

train-nvidia-grootn15:
  uv run lerobot-train \
      --dataset.repo_id={{ project_folder }}/dataset/felixmayor/record-lighter_v3.0 \
      --job_name=groot_candle_training \
      --output_dir={{ project_folder }}/outputs/gr00t_candle_training \
      --policy.type=groot \
      --policy.push_to_hub=false \
      --policy.repo_id={{ project_folder }}/outputs/groot_candle \
      --policy.tune_diffusion_model=false \
      --wandb.enable=false \
      --wandb.disable_artifact=true \
      --save_checkpoint=true \
      --log_freq=100 \
      --save_freq=5000 \
      --steps=1 \
      --policy.device=cuda \
      --batch_size=32
